<a href="https://colab.research.google.com/github/Harikrishna011/New-york-Taxi-fare-prediction_mlproject/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

Steps :

*   intsall required dataset
*  Download data from kaggle
*   view dataset files
*   Load training and testing  sets

In [13]:
!pip uninstall scikit-learn -y
!pip install -U scikit-learn

Found existing installation: scikit-learn 1.6.1
Uninstalling scikit-learn-1.6.1:
  Successfully uninstalled scikit-learn-1.6.1
Collecting scikit-learn
  Using cached scikit_learn-1.6.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.5.0)
Using cached scikit_learn-1.6.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
Installing collected packages: scikit-learn
Successfully installed scikit-learn-1.6.1

In [3]:
selected_cols = 'pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,fare_amount'.split(',')
selected_cols

['pickup_datetime',
 'pickup_longitude',
 'pickup_latitude',
 'dropoff_longitude',
 'dropoff_latitude',
 'passenger_count',
 'fare_amount']

In [4]:
import random

In [5]:


dtype={


  'pickup_longitude':'float32',
  'pickup_latitude':'float32',
  'dropoff_longitude':'float32',
  'dropoff_latitude':'float32',
  'passenger_count':'uint8',
  'fare_amount':'float32'
}

def skip_row(row_index):
  if row_index==0:
    return False
  return random.random()> 0.01
random.seed(42)


df=pd.read_csv('/content/drive/MyDrive/new-york-city-taxi-fare-prediction/train.csv',usecols=selected_cols,parse_dates=['pickup_datetime'],dtype=dtype,skiprows=skip_row)

In [6]:
test_df=pd.read_csv('/content/drive/MyDrive/new-york-city-taxi-fare-prediction/test.csv',dtype=dtype,parse_dates=['pickup_datetime'])
test_df

,key,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,2015-01-27 13:08:24.0000002,2015-01-27 13:08:24+00:00,-73.973320,40.763805,-73.981430,40.743835,1
1,2015-01-27 13:08:24.0000003,2015-01-27 13:08:24+00:00,-73.986862,40.719383,-73.998886,40.739201,1
2,2011-10-08 11:53:44.0000002,2011-10-08 11:53:44+00:00,-73.982521,40.751259,-73.979652,40.746140,1
3,2012-12-01 21:12:12.0000002,2012-12-01 21:12:12+00:00,-73.981163,40.767807,-73.990448,40.751637,1
4,2012-12-01 21:12:12.0000003,2012-12-01 21:12:12+00:00,-73.966049,40.789776,-73.988564,40.744427,1
...,...,...,...,...,...,...,...
9909,2015-05-10 12:37:51.0000002,2015-05-10 12:37:51+00:00,-73.968124,40.796997,-73.955643,40.780388,6
9910,2015-01-12 17:05:51.0000001,2015-01-12 17:05:51+00:00,-73.945511,40.803600,-73.960213,40.776371,6
9911,2015-04-19 20:44:15.0000001,2015-04-19 20:44:15+00:00,-73.991600,40.726608,-73.789742,40.647011,6
9912,2015-01-31 01:05:19.0000005,2015-01-31 01:05:19+00:00,-73.985573,40.735432,-73.939178,40.801731,6
9913,2015-01-18 14:06:23.0000006,2015-01-18 14:06:23+00:00,-73.988022,40.754070,-74.000282,40.759220,6

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 552450 entries, 0 to 552449
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   fare_amount        552450 non-null  float32
 1   pickup_datetime    552450 non-null  datetime64[ns, UTC]
 2   pickup_longitude   552450 non-null  float32
 3   pickup_latitude    552450 non-null  float32
 4   dropoff_longitude  552450 non-null  float32
 5   dropoff_latitude   552450 non-null  float32
 6   passenger_count    552450 non-null  uint8
dtypes: datetime64[ns, UTC](1), float32(5), uint8(1)
memory usage: 15.3 MB

In [8]:
df.describe()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,552450.000000,552450.000000,552450.000000,552450.000000,552450.000000,552450.000000
mean,11.354059,-72.497063,39.910500,-72.504326,39.934265,1.684983
std,9.810809,11.622035,8.041162,12.065184,9.226158,1.337664
min,-52.000000,-1183.362793,-3084.490234,-3356.729736,-2073.150635,0.000000
25%,6.000000,-73.992020,40.734875,-73.991425,40.733990,1.000000
50%,8.500000,-73.981819,40.752621,-73.980179,40.753101,1.000000
75%,12.500000,-73.967155,40.767036,-73.963737,40.768059,2.000000
max,499.000000,2420.209473,404.983337,2467.752686,3351.403076,208.000000

In [9]:
df['pickup_datetime'].min(),df['pickup_datetime'].max()

(Timestamp('2009-01-01 00:11:46+0000', tz='UTC'),
 Timestamp('2015-06-30 23:59:54+0000', tz='UTC'))

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
train_df,val_df=train_test_split(df,test_size=0.2,random_state=42)

In [16]:
len(train_df),len(val_df  )

(441960, 110490)

In [17]:
train_df=train_df.dropna()
val_df=val_df.dropna()

In [18]:
train_df.columns

Index(['fare_amount', 'pickup_datetime', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count'],
      dtype='object')

In [19]:
input_cols=[ 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count']

In [20]:
target_cols='fare_amount'

In [21]:
train_inputs=train_df[input_cols]
train_targets=train_df[target_cols]

In [22]:
val_inputs=val_df[input_cols]
val_targets=val_df[target_cols]

In [23]:
test_inputs=test_df[input_cols]

In [24]:
class MeanRegressor:
  def fit(self,inputs,targets):
    self.mean=targets.mean()
  def predict(self,inputs):
    return np.full(inputs.shape[0],self.mean)

In [25]:
mean_model=MeanRegressor()
mean_model.fit(train_inputs,train_targets)

In [26]:
mean_model.mean

11.354714

In [27]:
train_preds=mean_model.predict(train_inputs)
train_preds

array([11.354714, 11.354714, 11.354714, ..., 11.354714, 11.354714,
       11.354714], dtype=float32)

In [28]:
val_preds=mean_model.predict(val_inputs)
val_preds

array([11.354714, 11.354714, 11.354714, ..., 11.354714, 11.354714,
       11.354714], dtype=float32)

In [29]:
from sklearn.metrics import mean_squared_error

In [30]:
def rmse(targets,preds):
  return mean_squared_error(targets,preds)

In [31]:
train_rmse=rmse(train_targets,train_preds)
train_rmse

95.83982849121094

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
linear_model=LinearRegression()
linear_model.fit(train_inputs,train_targets)

LinearRegression()

In [34]:
train_preds=linear_model.predict(train_inputs)
train_preds

array([11.546237, 11.28461 , 11.28414 , ..., 11.458918, 11.284281,
       11.284448], dtype=float32)

In [35]:
rmse(train_targets,train_preds)

95.81732940673828

In [36]:
def predict_and_submit(model,test_inputs,fname):
  test_preds=model.predict(test_inputs)
  sub_df=pd.read_csv('/content/drive/MyDrive/new-york-city-taxi-fare-prediction/sample_submission.csv')
  sub_df['fare_amount']=test_preds
  sub_df.to_csv(fname,index=None)
  return sub_df

Feature Engineering

In [37]:
import pandas as pd

def add_dateparts(df, cols):


  # Ensure the column is in datetime format
  df[cols] = pd.to_datetime(df[cols])

  df[cols + '_year'] = df[cols].dt.year
  df[cols + '_month'] = df[cols].dt.month
  df[cols + '_day'] = df[cols].dt.day
  df[cols + '_weekday'] = df[cols].dt.weekday
  df[cols + '_hour'] = df[cols].dt.hour

In [38]:
cols='pickup_datetime'
add_dateparts(train_df,cols)
add_dateparts(val_df,cols)
add_dateparts(test_df,cols)

In [39]:
train_df

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour
353352,6.0,2015-04-12 03:40:38+00:00,-73.993652,40.741543,-73.977974,40.742352,4,2015,4,12,6,3
360070,3.7,2011-01-26 19:21:00+00:00,-73.993805,40.724579,-73.993805,40.724579,1,2011,1,26,2,19
372609,10.0,2012-10-03 10:40:17+00:00,-73.959160,40.780750,-73.969116,40.761230,1,2012,10,3,2,10
550895,8.9,2012-03-14 13:44:27+00:00,-73.952187,40.783951,-73.978645,40.772602,1,2012,3,14,2,13
444151,7.3,2012-02-05 15:33:00+00:00,-73.977112,40.746834,-73.991104,40.750404,2,2012,2,5,6,15
...,...,...,...,...,...,...,...,...,...,...,...,...
110268,9.3,2009-09-06 16:12:00+00:00,-73.987152,40.750633,-73.979073,40.763168,1,2009,9,6,6,16
259178,18.5,2009-04-12 09:58:56+00:00,-73.972656,40.764042,-74.013176,40.707840,2,2009,4,12,6,9
365838,10.1,2012-07-12 19:30:00+00:00,-73.991982,40.749767,-73.989845,40.720551,3,2012,7,12,3,19
131932,10.9,2011-02-17 18:33:00+00:00,-73.969055,40.761398,-73.990814,40.751328,1,2011,2,17,3,18
121958,9.5,2015-01-14 17:35:03+00:00,-73.983040,40.742142,-74.002510,40.727650,1,2015,1,14,2,17

In [40]:
val_df

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour
15971,14.000000,2015-05-19 09:27:24+00:00,-73.995834,40.759190,-73.973679,40.739086,1,2015,5,19,1,9
149839,6.500000,2010-04-10 15:07:51+00:00,-73.977386,40.738335,-73.976143,40.751205,1,2010,4,10,5,15
515867,49.570000,2009-07-25 14:11:00+00:00,-73.983910,40.749470,-73.787170,40.646645,1,2009,7,25,5,14
90307,49.700001,2011-11-11 19:09:21+00:00,-73.790794,40.643463,-73.972252,40.690182,1,2011,11,11,4,19
287032,8.500000,2015-03-09 18:06:44+00:00,-73.976593,40.761944,-73.991463,40.750309,2,2015,3,9,0,18
...,...,...,...,...,...,...,...,...,...,...,...,...
467556,6.100000,2010-04-03 20:16:00+00:00,-73.968567,40.761238,-73.983406,40.750019,3,2010,4,3,5,20
19482,7.300000,2010-04-26 00:32:00+00:00,-73.986725,40.755920,-73.985855,40.731171,1,2010,4,26,0,0
186063,4.500000,2009-05-21 08:13:16+00:00,0.000000,0.000000,0.000000,0.000000,1,2009,5,21,3,8
382260,32.900002,2011-07-07 16:10:59+00:00,-73.980057,40.760334,-73.872589,40.774300,1,2011,7,7,3,16
18838,11.500000,2015-02-27 12:10:08+00:00,-73.955406,40.782417,-73.960434,40.767666,1,2015,2,27,4,12

In [41]:
test_df

,key,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour
0,2015-01-27 13:08:24.0000002,2015-01-27 13:08:24+00:00,-73.973320,40.763805,-73.981430,40.743835,1,2015,1,27,1,13
1,2015-01-27 13:08:24.0000003,2015-01-27 13:08:24+00:00,-73.986862,40.719383,-73.998886,40.739201,1,2015,1,27,1,13
2,2011-10-08 11:53:44.0000002,2011-10-08 11:53:44+00:00,-73.982521,40.751259,-73.979652,40.746140,1,2011,10,8,5,11
3,2012-12-01 21:12:12.0000002,2012-12-01 21:12:12+00:00,-73.981163,40.767807,-73.990448,40.751637,1,2012,12,1,5,21
4,2012-12-01 21:12:12.0000003,2012-12-01 21:12:12+00:00,-73.966049,40.789776,-73.988564,40.744427,1,2012,12,1,5,21
...,...,...,...,...,...,...,...,...,...,...,...,...
9909,2015-05-10 12:37:51.0000002,2015-05-10 12:37:51+00:00,-73.968124,40.796997,-73.955643,40.780388,6,2015,5,10,6,12
9910,2015-01-12 17:05:51.0000001,2015-01-12 17:05:51+00:00,-73.945511,40.803600,-73.960213,40.776371,6,2015,1,12,0,17
9911,2015-04-19 20:44:15.0000001,2015-04-19 20:44:15+00:00,-73.991600,40.726608,-73.789742,40.647011,6,2015,4,19,6,20
9912,2015-01-31 01:05:19.0000005,2015-01-31 01:05:19+00:00,-73.985573,40.735432,-73.939178,40.801731,6,2015,1,31,5,1
9913,2015-01-18 14:06:23.0000006,2015-01-18 14:06:23+00:00,-73.988022,40.754070,-74.000282,40.759220,6,2015,1,18,6,14

In [42]:
import numpy as np

def haversine_np(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points
    on the earth (specified in decimal degrees)

    All args must be of equal length.

    """
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2

    c = 2 * np.arcsin(np.sqrt(a))
    km = 6378.137 * c
    return km

In [43]:
def add_trip_distance(df):
  df['trip_distance']=haversine_np(df['pickup_longitude'],df['pickup_latitude'],df['dropoff_longitude'],df['dropoff_latitude'])

In [44]:
add_trip_distance(train_df)
add_trip_distance(val_df)
add_trip_distance(test_df)

In [45]:
jfk_lonlat = -73.7781, 40.6413
lga_lonlat = -73.8740, 40.7769
ewr_lonlat = -74.1745,40.6895
met_lonlat = -73.9632, 40.7794
wtc_lonlat=-74.0099,40.7126

In [46]:
def add_landmark_dropoff_distance(df,landmark_name,landmark_lonlat):
  lon,lat=landmark_lonlat
  df[f'{landmark_name}_dropoff_distance']=haversine_np(lon,lat,df['dropoff_longitude'],df['dropoff_latitude'])

In [47]:
def add_landmarks(a_df):
  landmarks=[('jfk',jfk_lonlat),('lga',lga_lonlat),('ewr',ewr_lonlat),('met',met_lonlat),('wtc',wtc_lonlat)]
  for name,lonlat in landmarks:
    add_landmark_dropoff_distance(a_df,name,lonlat)

In [50]:
add_landmarks(train_df)

In [48]:
add_landmarks(val_df)

In [49]:
add_landmarks(test_df)

In [51]:
def remove_outliers(df):
  return df[(df['fare_amount']>=1.)&
            (df['fare_amount']<=500.)&
            (df['pickup_longitude']>=-75)&
            (df['pickup_longitude']<=-72)&
            (df['dropoff_longitude']>=-75)&
            (df['dropoff_longitude']<=-72)&
            (df['pickup_latitude']<=42)&
            (df['pickup_latitude']>=40)&
            (df['dropoff_latitude']>=40)&
            (df['dropoff_latitude']<=42)&
            (df['passenger_count']>=1)&
            (df['passenger_count']<=6)
            ]

In [52]:
train_df=remove_outliers(train_df)

In [53]:
val_df=remove_outliers(val_df)

In [54]:
train_df.columns

Index(['fare_amount', 'pickup_datetime', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count',
       'pickup_datetime_year', 'pickup_datetime_month', 'pickup_datetime_day',
       'pickup_datetime_weekday', 'pickup_datetime_hour', 'trip_distance',
       'jfk_dropoff_distance', 'lga_dropoff_distance', 'ewr_dropoff_distance',
       'met_dropoff_distance', 'wtc_dropoff_distance'],
      dtype='object')

In [56]:
input_cols=[ 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count',
       'pickup_datetime_year', 'pickup_datetime_month', 'pickup_datetime_day',
       'pickup_datetime_weekday', 'pickup_datetime_hour', 'trip_distance',
       'jfk_dropoff_distance', 'lga_dropoff_distance', 'ewr_dropoff_distance',
       'met_dropoff_distance', 'wtc_dropoff_distance']

In [57]:
target_cols='fare_amount'

In [58]:
train_inputs=train_df[input_cols]
train_targets=train_df[target_cols]

In [59]:
val_inputs=val_df[input_cols]
val_targets=val_df[target_cols]

In [60]:
test_inputs=test_df[input_cols]

In [61]:
def evaluate(model):
  train_preds=model.predict(train_inputs)
  val_preds=model.predict(val_inputs)
  train_rmse=rmse(train_targets,train_preds)
  val_rmse=rmse(val_targets,val_preds)
  return train_rmse,val_rmse,train_preds,val_preds

In [62]:
from sklearn.linear_model import Ridge

In [63]:
!pip install scipy==1.9.0

Collecting scipy==1.9.0
  Downloading scipy-1.9.0.tar.gz (42.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 MB 17.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [64]:
model1=Ridge(random_state=42,alpha=0.9,solver='svd')
model1.fit(train_inputs,train_targets)

Ridge(alpha=0.9, random_state=42, solver='svd')

In [65]:
evaluate(model1)

(25.495572320704728,
 27.22591293197293,
 array([ 8.12923748,  4.11617153,  8.75015917, ..., 10.47209122,
         8.23071296, 10.58695499]),
 array([10.91913814,  6.2050743 , 46.21884569, ...,  8.04612831,
        25.56777559,  8.45283274]))

In [66]:
train_inputs.shape

(431098, 16)

In [67]:
predict_and_submit(model1,test_inputs,'submission1.csv')

                              key  fare_amount
0     2015-01-27 13:08:24.0000002    10.081973
1     2015-01-27 13:08:24.0000003    11.400097
2     2011-10-08 11:53:44.0000002     5.356944
3     2012-12-01 21:12:12.0000002     8.763522
4     2012-12-01 21:12:12.0000003    14.609350
...                           ...          ...
9909  2015-05-10 12:37:51.0000002     9.024145
9910  2015-01-12 17:05:51.0000001    11.217691
9911  2015-04-19 20:44:15.0000001    47.927673
9912  2015-01-31 01:05:19.0000005    22.600264
9913  2015-01-18 14:06:23.0000006     8.981939

[9914 rows x 2 columns]

In [68]:
from sklearn.ensemble import RandomForestRegressor

In [69]:
model2=RandomForestRegressor(random_state=42,n_jobs=-1,max_depth=10,n_estimators=100)
model2.fit(train_inputs,train_targets)

RandomForestRegressor(max_depth=10, n_jobs=-1, random_state=42)

In [70]:
evaluate(model2)

(12.922686301327724,
 17.314369165198503,
 array([ 6.99399909,  9.09865173,  9.09379987, ..., 10.43082088,
         7.7821555 , 10.400694  ]),
 array([12.65433613,  6.14604627, 47.31069124, ...,  8.36589355,
        29.27069612,  8.24300598]))

In [71]:
predict_and_submit(model2,test_inputs,'submission2.csv')

                              key  fare_amount
0     2015-01-27 13:08:24.0000002    10.479748
1     2015-01-27 13:08:24.0000003    10.468653
2     2011-10-08 11:53:44.0000002     5.046148
3     2012-12-01 21:12:12.0000002     8.481902
4     2012-12-01 21:12:12.0000003    14.300694
...                           ...          ...
9909  2015-05-10 12:37:51.0000002     8.694722
9910  2015-01-12 17:05:51.0000001    12.535128
9911  2015-04-19 20:44:15.0000001    55.355344
9912  2015-01-31 01:05:19.0000005    21.467722
9913  2015-01-18 14:06:23.0000006     6.822782

[9914 rows x 2 columns]

In [72]:
from xgboost import XGBRegressor

In [73]:
model3=XGBRegressor(random_state=42,n_jobs=-1,max_depth=5,n_estimators=200,learning_rate=0.1,objective='reg:squarederror')
model3.fit(train_inputs,train_targets)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=5, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=200, n_jobs=-1,
             num_parallel_tree=None, random_state=42, ...)

In [74]:
evaluate(model3)

(12.469317436218262,
 16.177141189575195,
 array([ 6.51957 ,  8.944513, 10.146399, ..., 11.402378,  8.855036,
        10.313538], dtype=float32),
 array([14.594226 ,  6.0985413, 48.717716 , ...,  7.6249237, 30.246498 ,
         8.783627 ], dtype=float32))

In [75]:
predict_and_submit(model3,test_inputs,'submission3.csv')

                              key  fare_amount
0     2015-01-27 13:08:24.0000002    11.055681
1     2015-01-27 13:08:24.0000003    11.117402
2     2011-10-08 11:53:44.0000002     4.797336
3     2012-12-01 21:12:12.0000002     8.497568
4     2012-12-01 21:12:12.0000003    15.783599
...                           ...          ...
9909  2015-05-10 12:37:51.0000002     8.889234
9910  2015-01-12 17:05:51.0000001    11.349341
9911  2015-04-19 20:44:15.0000001    54.518284
9912  2015-01-31 01:05:19.0000005    19.371681
9913  2015-01-18 14:06:23.0000006     6.620957

[9914 rows x 2 columns]

In [76]:
import matplotlib.pyplot as plt

In [77]:
def test_params(ModelClass,**params):
  model=ModelClass(**params)
  model.fit(train_inputs,train_targets)
  train_rmse=mean_squared_error(model.predict(train_inputs),train_targets,squared=False)
  val_rmse=mean_squared_error(model.predict(val_inputs),val_targets,squared=False)
  return train_rmse,val_rmse

In [78]:
def test_param_and_plot(ModelClass,param_name,param_values,**other_params):
  train_errors,val_errors=[],[]
  for value in param_values:
    params=dict(other_params)
    params[param_name]=value
    train_rmse,val_rmse=test_params(ModelClass,**params)
    train_errors.append(train_rmse)
    val_errors.append(val_rmse)
  plt.figure(figsize=(10,6))
  plt.title('overfitting curve'+param_name)
  plt.plot(param_values,train_errors,'b-o')
  plt.plot(param_values,val_errors,'r-o')
  plt.xlabel(param_name)
  plt.ylabel('rmse')
  plt.legend(['Training','Validation'])

In [79]:
best_params={
    'random_state':42,
    'n_jobs':-1,
    'learning_rate':0.05,

    'objective':'reg:squarederror'
}

In [80]:

test_param_and_plot(XGBRegressor,'num_estimators',[100,200,400],**best_params)

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [12:57:17] WARNING: /workspace/src/learner.cc:740:
Parameters: { "num_estimators" } are not used.

  warnings.warn(smsg, UserWarning)

TypeError: got an unexpected keyword argument 'squared'

In [ ]:
best_params['num_estimators']=100

In [ ]:
test_param_and_plot(XGBRegressor,'max_depth',[3,5,6,7],**best_params)

In [ ]:
best_params['max_depth']=7

In [ ]:
test_param_and_plot(XGBRegressor,'learning_rate',[0.05,0.1,0.2],**best_params)

In [ ]:
best_params['learning_rate']=0.1

In [ ]:
xgb_model_final=XGBRegressor(random_state=42,
                             n_jobs=-1,
                             learning_rate=0.08,
                             objective='reg:squarederror',
                             n_estimators=500,
                             max_depth=8,
                             subsample=0.8,
                             colsample_bytree=0.8
                             )

In [ ]:
xgb_model_final.fit(train_inputs,train_targets)

In [ ]:
evaluate(xgb_model_final)

In [ ]:
predict_and_submit(xgb_model_final,test_inputs,'xgb_submission.csv')

In [ ]:
!git config --global user.email "rangisettiharikrishna@gmail.com"
!git config --global user.name "Harikrishna011"